spring:
  application:
    name: smart-recs
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_recs
    username: postgres
    password: postgres
#  datasource:
#    url: jdbc:postgresql://192.168.1.132:5432/smart_recs
#    username: postgres
#    password: 6HMFsyBPLcHFLBoZBXIM
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: DEBUG