spring:
  application:
    name: smart-recs
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_recs
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true